[package]
name = "geo-bevy"
description = "Generate Bevy meshes from `geo` types"
version = "0.3.0"
authors = ["Corey Farwell <coreyf@rwell.org>"]
edition = "2021"
repository = "https://github.com/frewsxcv/geo-bevy"
license = "MIT OR Apache-2.0"

[dependencies]
bevy_log = "0.10"
bevy_render = "0.10"
geo = { git = "https://github.com/georust/geo.git" }
